-- RETRIEVE A LIST OF EMPLOYEES ORDERED BY DEPARTMENT NAME, AND WITHIN
-- EACH DEPARTMENT ORDERED ALPHABETICALLY IN DESCENDING ORDER BY LAST NAME.

SELECT *
FROM EMPLOYEES
JOIN DEPARTMENTS
ON DEP_ID = DEPT_ID_DEP
ORDER BY DEP_NAME, L_NAME DESC;
