-- RETRIEVE A LIST OF EMPLOYEES ORDERED IN DESCENDING ORDER BY
-- DEPARTMENT ID AND WITHIN EACH DEPARTMENT ORDERED ALPHABETICALLY IN
-- DESCENDING ORDER BY LAST NAME.
SELECT * FROM EMPLOYEES
ORDER BY DEP_ID DESC, L_NAME DESC;