--IN QUERY 5D LIMIT THE RESULT TO DEPARTMENTS WITH FEWER THAN 4 EMPLOYEES.
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY 
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;
